# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - api-desafiodiadorock

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build src/DesafioDiaDoRock.PublicApi/DesafioDiaDoRock.PublicApi.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/DesafioDiaDoRock.PublicApi/DesafioDiaDoRock.PublicApi.csproj -c Release -o ${{env.DOTNET_ROOT}}/api-desafiodiadorock

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-api-app
          path: ${{env.DOTNET_ROOT}}/api-desafiodiadorock

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-api-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-desafiodiadorock'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BFC982AFC2EE44BF933EE86A57FE4EF9 }}

      - name: Set environment variables
        run: |
          echo "BackendUrl=https://api-desafiodiadorock-geh0e9e3gkfpbzgg.eastus-01.azurewebsites.net/" >> $GITHUB_ENV
          echo "FrontendUrl=https://ui-desafiodiarock.raphaelfalves.dev/" >> $GITHUB_ENV
          echo "GoogleApiKey=AIzaSyAqN-qevL5e5RtlGTbcUwEVkh7vi6MPcuM" >> $GITHUB_ENV
